### ISSUE TITLE
Issue with URL

### ISSUE THREAD

**Issue by defjam903** [orionstudt/ConnectWise.Http#1]
could you tell me what type of URL should be sent over to the connect wise system my ticket request comes back with null but that tells me that I may not be calling the correct REST URL?

**Comment by orionstudt** [comment]
Hi @defjam903, are you still having a problem with this? Sorry I haven't been super active.

Can you provide anymore clarification on what endpoint you are trying to access, whether or not you are on-prem or cloud hosted, and how you are trying to access that endpoint?

**Comment by orionstudt** [comment]
I'm going to close this - I wanted to give you the same amount of time it took me to respond. Please feel free to re-open if you're still having the issue and have some more information.

**Comment by defjam903** [comment]
You can close this request I found a workaround and gave up on some of it.

On Mar 20, 2018 8:20 PM, "Josh Studt" <notifications@github.com> wrote:

I'm going to close this - I wanted to give you the same amount of time it
took me to respond. Please feel free to re-open if you're still having the
issue and have some more information.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/orionstudt/ConnectWise.Http/issues/1#issuecomment-374809958>,
or mute the thread

**Comment by orionstudt** [comment]
Hi @defjam903, just wanted to let you know that I did in fact find this bug and resolve it about a month ago - so in the most recent NuGet this should no longer be an issue.
