### ISSUE TITLE
GetRequest OrderBy and PageSize parameters erroring

### ISSUE THREAD

**Issue by Venators** [orionstudt/ConnectWise.Http#13]
Hi there,

I'm using version 1.1.1 and I'm making a ServiceModule.Tickets.GetRequest. Normally this works just fine, and I'm wanting to add an OrderBy and PageSize parameters, but when I do, the request errors. 

Based on the CWRequestConditions class:
![image](https://user-images.githubusercontent.com/20661886/185511968-7a112eac-8b8a-4b83-8dfd-41937e42c3a6.png)
I assume that I'd structure the request conditions like so:
![image](https://user-images.githubusercontent.com/20661886/185512055-01382906-f85f-4be4-87b1-e1eb2201d20e.png)
The URL constructed by the GetRequest method looks correct to me:
service/tickets?conditions=status/name!=%22Closed%22%20AND%20board/name%20=%22Service%20Alerts%22%20AND%20type/id=195%20AND%20_info/enteredBy=%22API%20Account%22%26orderBy=id%20desc%26pageSize=100
But I end up with the following error:
![image](https://user-images.githubusercontent.com/20661886/185512468-9aa3750d-cbb7-4783-8888-a302ff77fb3f.png)

Am I doing something wrong or is this an issue with the library? Hoping someone has a working example or can point me in the right direction!

Cheers,
David

**Comment by ajwaka** [comment]
I tried your same call - and the output is correct.  But I had to UrlDecode
your string.  For some reason the ampersand's before orderby and pageSize
are urlencoded and that's what's throwing it off.    Here's a screenshot of
your url - UrlDecoded (top) and my setup - you can see my EndPoint  didn't
UrlEncode the ampersands.  Are you doing something after setting up your
conditions?

[image: image.png]

<https://www.foremostmedia.com/portals/0/emailers/email-sig/fm_logo_signature.png>
Andy Walker | Founder, CIO, CTO
P : 608.758.4841
E : ***@***.***
207 N. Academy Street, Suite #200 • Janesville, WI 53548
WEB DEVELOPMENT <https://www.foremostmedia.com/services/website-development>
 | MARKETING AUTOMATION
<https://www.foremostmedia.com/services/marketing-automation> | ONLINE
MARKETING <https://www.foremostmedia.com/services/online-marketing>
<http://www.facebook.com/foremostmediausa>
<http://twitter.com/#!/foremostmedia>
<http://www.linkedin.com/company/foremost-media-inc>

**Comment by Venators** [comment]
Hi Andy,
Thank you for your reply.
I was URL encoding the request object endpoint as this is required when retrieving existing tickets by summary, but in hindsight, was clearly not needed in this use case. 
After removing the URL encoding the request works as expected.
Thanks again!

**Comment by orionstudt** [comment]
Thanks for catching that @ajwaka , I was wondering why there was no `&` in the query conditions. Glad it's working now!
