### ISSUE TITLE
CWAPISettings not exposing ClientID?

### ISSUE THREAD

**Issue by grinsfelder** [orionstudt/ConnectWise.Http#7]
I'm probably doing something wrong, but when I did the nu-get package install, the version installed doesn't expose ClientID 

From Object Browser in VS2017:

![image](https://user-images.githubusercontent.com/3855573/63534076-e4f64880-c4d3-11e9-8300-ce96fd370946.png)

![image](https://user-images.githubusercontent.com/3855573/63534133-0eaf6f80-c4d4-11e9-8f86-b9b3f219fe05.png)

**Comment by orionstudt** [comment]
Hi, you're not doing anything wrong - I've been meaning to publish a new package but I've had some personal things going on. Thank you for bringing it up though as I have some time right now and can work on getting it up within the hour.

**Comment by orionstudt** [comment]
Just pushed to NuGet it is currently validating. Let me know if you have any issues!

**Comment by grinsfelder** [comment]
Thanks!  You rock!!
