### ISSUE TITLE
Compaby billing rate

### ISSUE THREAD

**Issue by RiaVteB** [orionstudt/ConnectWise.Http#9]
Hi, I am looking for the CompanyBillingRate table. Is it possible to add this to the solution?
Hope anyone can help

**Comment by orionstudt** [comment]
Hi! Can you provide any more input on what endpoint I am missing?

**Comment by RiaVteB** [comment]
Hi Josh,

 

I could not update the invoicetemplate

 

","billingTerms":{"id":2,"name":"Netto 14 dagen"},"invoiceTemplate":{"id":10,"name":"Producten","_info":{"billingTerms_Href":"https://api-eu.myconnectwise.net/v4_6_release/apis/3.0/finance/invoiceTemplateSetups/10"}},"billToCompany":{"id":20525,"identifier":"14921","name":"123inkt.nl","_info":{"company_href":"https://api-

 

Now I see the code of the getrequest again I think I can.

 

Ria

 

Van: Josh Studt <notifications@github.com> 
Verzonden: donderdag 30 januari 2020 21:57
Aan: orionstudt/ConnectWise.Http <ConnectWise.Http@noreply.github.com>
CC: RiaVteB <riavlasveld@friendsys.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [orionstudt/ConnectWise.Http] Compaby billing rate (#9)

 

Hi! Can you provide any more input on what endpoint I am missing?

**Comment by orionstudt** [comment]
Hi @RiaVteB , were you able to resolve this? Did you find the endpoint you needed in the existing modules, or did you need to customize the request? If I'm missing an endpoint it could maybe be added.
